$axure.loadCurrentPage({
  "url":"backyard.html",
  "generationDate":new Date(1475166369788.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/index/bg.jpg",
    "width":1024,
    "height":426},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"8add25c63f524ed58e5ee87ddfca27e5",
    "type":"Axure:Page",
    "name":"Backyard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"cover",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d2d9522b1e3448b3897780675ad1c357",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":1080,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351e16a705a6443cb83c40e79f74e801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":1080,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u10.png"}},
{
          "id":"d22576d296a74029a80e2bc29c3a89a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1080,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff82c039a9b1469d99009d3d5e340ff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1080,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u8.png"}},
{
          "id":"6d409c1baf3c40e7920436b4a3b46be8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":23,
              "y":64},
            "size":{
              "width":340,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e07f2aefbaa447c4aeffe26ea17224ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":23,
                  "y":64},
                "size":{
                  "width":340,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u22.jpg"}},
{
          "id":"fe5df249d7e34454b184105c6bbdf522",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":1080,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d75266955148c7b33199aa2e5df60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":1080,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u12.png"}},
{
          "id":"0086f1c0fb274482a50cce86fe5602e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":710,
              "y":170},
            "size":{
              "width":190,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba3a166731e0400aa838dd7fffc7e247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":710,
                  "y":170},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pinni_b/u8.png"}},
{
          "id":"1442065a51f3409b914cd9d2500625bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":203,
              "y":230},
            "size":{
              "width":677,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e742a309ab14aa980a7080969ec2472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":203,
                  "y":230},
                "size":{
                  "width":677,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pinni_b/u10.png"}},
{
          "id":"83f122af0d8b4c369cb63f8dbdab0b98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":405,
              "y":240},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c7db1a8a224ed18d83bb8e6eac856c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":405,
                  "y":240},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pinni_b/u14.png"}},
{
          "id":"942f3a46737940898ac431dba1f2ec52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":262,
              "y":290},
            "size":{
              "width":560,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade55eec7b83456f834a312a35da7fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":262,
                  "y":290},
                "size":{
                  "width":560,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/p2_s_u24.jpg"}},
{
          "id":"ca8ee37f5b7b4f97a94bdadd8a379932",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":920,
              "y":10},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c601653fa857437887743138e8f60e71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":920,
                  "y":10},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pinni_b/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d2d9522b1e3448b3897780675ad1c357":{
      "scriptId":"u0"},
    "351e16a705a6443cb83c40e79f74e801":{
      "scriptId":"u1"},
    "d22576d296a74029a80e2bc29c3a89a6":{
      "scriptId":"u2"},
    "ff82c039a9b1469d99009d3d5e340ff7":{
      "scriptId":"u3"},
    "6d409c1baf3c40e7920436b4a3b46be8":{
      "scriptId":"u4"},
    "e07f2aefbaa447c4aeffe26ea17224ec":{
      "scriptId":"u5"},
    "fe5df249d7e34454b184105c6bbdf522":{
      "scriptId":"u6"},
    "66d75266955148c7b33199aa2e5df60e":{
      "scriptId":"u7"},
    "0086f1c0fb274482a50cce86fe5602e1":{
      "scriptId":"u8"},
    "ba3a166731e0400aa838dd7fffc7e247":{
      "scriptId":"u9"},
    "1442065a51f3409b914cd9d2500625bb":{
      "scriptId":"u10"},
    "2e742a309ab14aa980a7080969ec2472":{
      "scriptId":"u11"},
    "83f122af0d8b4c369cb63f8dbdab0b98":{
      "scriptId":"u12"},
    "85c7db1a8a224ed18d83bb8e6eac856c":{
      "scriptId":"u13"},
    "942f3a46737940898ac431dba1f2ec52":{
      "scriptId":"u14"},
    "ade55eec7b83456f834a312a35da7fa8":{
      "scriptId":"u15"},
    "ca8ee37f5b7b4f97a94bdadd8a379932":{
      "scriptId":"u16"},
    "c601653fa857437887743138e8f60e71":{
      "scriptId":"u17"}}});