$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1475166369543.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/index/bg.jpg",
    "width":1024,
    "height":426},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"97ab1a50dc1a46c09dbf2b405acd8b5b",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"cover",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a2e08b9f0874936b1cf0cb21c367d4f",
          "label":"Back3 S",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":717,
              "y":230},
            "size":{
              "width":354,
              "height":410},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a6da883a604f50b564774d55037986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":717,
                  "y":230},
                "size":{
                  "width":354,
                  "height":410},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/back3_s_u0.png"}},
{
          "id":"120f95b7ac6e4483bb2e002f742ae87f",
          "label":"P3 S",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":737,
              "y":250},
            "size":{
              "width":313,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d08414177ae3440a8683d17b47363f87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":737,
                  "y":250},
                "size":{
                  "width":313,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 Back 3 B,<br>P3 B",
                      "objectsToFades":[{
                          "objectPath":["9793c5e343d2498bbbb85c5fee95a210"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1a17eff9fe384d0190a795b70c78f5df"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/index/p3_s_u2.jpg"}},
{
          "id":"1c97a455c986486b909e3871ffdd953d",
          "label":"Back1 S",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":353,
              "height":410},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87efda94366b415da557529411026823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":230},
                "size":{
                  "width":353,
                  "height":410},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/back1_s_u4.png"}},
{
          "id":"9900778ae77f4c77b311cda17c7fdb64",
          "label":"Back2 S",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":363,
              "y":230},
            "size":{
              "width":354,
              "height":410},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39da703dd231407c8d167abb1c32fe0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":363,
                  "y":230},
                "size":{
                  "width":354,
                  "height":410},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/back3_s_u0.png"}},
{
          "id":"1053cc02b78f452b918a435de4dea875",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1080,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e82fbe76003e4660bb34688b6263cc93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1080,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u8.png"}},
{
          "id":"c087fcbce2354ebfad6ab77cd892747b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":1080,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8147f387fcd409bb8adb09e889bc0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":1080,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u10.png"}},
{
          "id":"eab00b8818a24a57b76121fd6854d1f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"36px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":1080,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af0ca1b163654c25ac82c3788606e334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"36px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":1080,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u12.png"}},
{
          "id":"c75325f56f2a4f5c846497de3865a9a6",
          "label":"P1 S",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":250},
            "size":{
              "width":313,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6ed8d6157f428487174bb82bd36c33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":250},
                "size":{
                  "width":313,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 Back 1 B,<br>P1 B",
                      "objectsToFades":[{
                          "objectPath":["8fbd3d8c65924064939229c57b64f537"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f103f78d06734b2a97a01b3225835505"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/index/p1_s_u14.jpg"}},
{
          "id":"93de5ee4290040a8aa77b05e4e62832d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":80,
              "y":570},
            "size":{
              "width":213,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e2aa6d622214119a897a855fd7e2c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":80,
                  "y":570},
                "size":{
                  "width":213,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u16.png"}},
{
          "id":"a7e4be0815a14bd382a7d763d8d8824e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":433,
              "y":570},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ac180aa16964a9885862e1cf7ec0a1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":433,
                  "y":570},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u18.png"}},
{
          "id":"a6c6f4fe8c1a45da8f961479fe57d870",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":787,
              "y":570},
            "size":{
              "width":213,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03085d550c1949aaa4f31155e0001010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":787,
                  "y":570},
                "size":{
                  "width":213,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u16.png"}},
{
          "id":"44a827c8e3f74b689d9bb3c52c1bba34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":23,
              "y":64},
            "size":{
              "width":340,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bc5a280337a4c81ac7126feb1790268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":23,
                  "y":64},
                "size":{
                  "width":340,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u22.jpg"}},
{
          "id":"ba0e5ae1adac4e00b9f79eca25b9b5b0",
          "label":"P2 S",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":383,
              "y":250},
            "size":{
              "width":314,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b64ead38869540c4af69e90ed62e697a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":383,
                  "y":250},
                "size":{
                  "width":314,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 Back 2 B,<br>P2 B",
                      "objectsToFades":[{
                          "objectPath":["211bf57c19d1467893451ec3721d0ae3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c5639ca31be84464b5cd238b7afe7715"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/index/p2_s_u24.jpg"}},
{
          "id":"8fbd3d8c65924064939229c57b64f537",
          "label":"Back 1 B",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":530,
              "height":495},
            "visible":false,
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db2af1cea5f4f2296c133c75af9b6c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":230},
                "size":{
                  "width":530,
                  "height":495},
                "visible":false,
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 P1 B,<br>Back 1 B",
                      "objectsToFades":[{
                          "objectPath":["f103f78d06734b2a97a01b3225835505"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8fbd3d8c65924064939229c57b64f537"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/index/back_1_b_u26.png"}},
{
          "id":"f103f78d06734b2a97a01b3225835505",
          "label":"P1 B",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":260},
            "size":{
              "width":470,
              "height":435},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e94b21212e548c08e897a42d7906581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":260},
                "size":{
                  "width":470,
                  "height":435},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Pinni B",
                      "target":{
                        "targetType":"page",
                        "url":"pinni_b.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/p1_s_u14.jpg"}},
{
          "id":"211bf57c19d1467893451ec3721d0ae3",
          "label":"Back 2 B",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":275,
              "y":230},
            "size":{
              "width":530,
              "height":495},
            "visible":false,
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3105d11b13ad4a249547fe4b5990dbdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":275,
                  "y":230},
                "size":{
                  "width":530,
                  "height":495},
                "visible":false,
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 Back 2 B,<br>P2 B",
                      "objectsToFades":[{
                          "objectPath":["211bf57c19d1467893451ec3721d0ae3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c5639ca31be84464b5cd238b7afe7715"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/index/back_1_b_u26.png"}},
{
          "id":"9793c5e343d2498bbbb85c5fee95a210",
          "label":"Back 3 B",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":540,
              "y":230},
            "size":{
              "width":530,
              "height":495},
            "visible":false,
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed4514b9b9d6465aa422f2518799599c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":540,
                  "y":230},
                "size":{
                  "width":530,
                  "height":495},
                "visible":false,
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 Back 3 B,<br>P3 B",
                      "objectsToFades":[{
                          "objectPath":["9793c5e343d2498bbbb85c5fee95a210"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1a17eff9fe384d0190a795b70c78f5df"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/index/back_1_b_u26.png"}},
{
          "id":"c5639ca31be84464b5cd238b7afe7715",
          "label":"P2 B",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":305,
              "y":260},
            "size":{
              "width":470,
              "height":435},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3b3beb7b9e745668791b7de337cf4d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":305,
                  "y":260},
                "size":{
                  "width":470,
                  "height":435},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Backyard",
                      "target":{
                        "targetType":"page",
                        "url":"backyard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/p2_s_u24.jpg"}},
{
          "id":"1a17eff9fe384d0190a795b70c78f5df",
          "label":"P3 B",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":570,
              "y":260},
            "size":{
              "width":470,
              "height":435},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9017e90ac5e443d992ad9e52c201c8ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":570,
                  "y":260},
                "size":{
                  "width":470,
                  "height":435},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Main building",
                      "target":{
                        "targetType":"page",
                        "url":"main_building.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/p3_s_u2.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a2e08b9f0874936b1cf0cb21c367d4f":{
      "scriptId":"u0"},
    "24a6da883a604f50b564774d55037986":{
      "scriptId":"u1"},
    "120f95b7ac6e4483bb2e002f742ae87f":{
      "scriptId":"u2"},
    "d08414177ae3440a8683d17b47363f87":{
      "scriptId":"u3"},
    "1c97a455c986486b909e3871ffdd953d":{
      "scriptId":"u4"},
    "87efda94366b415da557529411026823":{
      "scriptId":"u5"},
    "9900778ae77f4c77b311cda17c7fdb64":{
      "scriptId":"u6"},
    "39da703dd231407c8d167abb1c32fe0d":{
      "scriptId":"u7"},
    "1053cc02b78f452b918a435de4dea875":{
      "scriptId":"u8"},
    "e82fbe76003e4660bb34688b6263cc93":{
      "scriptId":"u9"},
    "c087fcbce2354ebfad6ab77cd892747b":{
      "scriptId":"u10"},
    "f8147f387fcd409bb8adb09e889bc0a7":{
      "scriptId":"u11"},
    "eab00b8818a24a57b76121fd6854d1f5":{
      "scriptId":"u12"},
    "af0ca1b163654c25ac82c3788606e334":{
      "scriptId":"u13"},
    "c75325f56f2a4f5c846497de3865a9a6":{
      "scriptId":"u14"},
    "cc6ed8d6157f428487174bb82bd36c33":{
      "scriptId":"u15"},
    "93de5ee4290040a8aa77b05e4e62832d":{
      "scriptId":"u16"},
    "6e2aa6d622214119a897a855fd7e2c9d":{
      "scriptId":"u17"},
    "a7e4be0815a14bd382a7d763d8d8824e":{
      "scriptId":"u18"},
    "8ac180aa16964a9885862e1cf7ec0a1b":{
      "scriptId":"u19"},
    "a6c6f4fe8c1a45da8f961479fe57d870":{
      "scriptId":"u20"},
    "03085d550c1949aaa4f31155e0001010":{
      "scriptId":"u21"},
    "44a827c8e3f74b689d9bb3c52c1bba34":{
      "scriptId":"u22"},
    "7bc5a280337a4c81ac7126feb1790268":{
      "scriptId":"u23"},
    "ba0e5ae1adac4e00b9f79eca25b9b5b0":{
      "scriptId":"u24"},
    "b64ead38869540c4af69e90ed62e697a":{
      "scriptId":"u25"},
    "8fbd3d8c65924064939229c57b64f537":{
      "scriptId":"u26"},
    "1db2af1cea5f4f2296c133c75af9b6c5":{
      "scriptId":"u27"},
    "f103f78d06734b2a97a01b3225835505":{
      "scriptId":"u28"},
    "0e94b21212e548c08e897a42d7906581":{
      "scriptId":"u29"},
    "211bf57c19d1467893451ec3721d0ae3":{
      "scriptId":"u30"},
    "3105d11b13ad4a249547fe4b5990dbdc":{
      "scriptId":"u31"},
    "9793c5e343d2498bbbb85c5fee95a210":{
      "scriptId":"u32"},
    "ed4514b9b9d6465aa422f2518799599c":{
      "scriptId":"u33"},
    "c5639ca31be84464b5cd238b7afe7715":{
      "scriptId":"u34"},
    "c3b3beb7b9e745668791b7de337cf4d0":{
      "scriptId":"u35"},
    "1a17eff9fe384d0190a795b70c78f5df":{
      "scriptId":"u36"},
    "9017e90ac5e443d992ad9e52c201c8ea":{
      "scriptId":"u37"}}});