$axure.loadCurrentPage({
  "url":"main_building.html",
  "generationDate":new Date(1475166369869.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/index/bg.jpg",
    "width":1024,
    "height":426},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"6646b3837acc4a189928e9bde7b9e998",
    "type":"Axure:Page",
    "name":"Main building",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"cover",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55cef320cd7c439b9aa2c5aeff7410ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":1080,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce592be8a6bf44c2b0b8987d4222f8f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":1080,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u10.png"}},
{
          "id":"62e4644528f4438da14445d7704b6327",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1080,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f11ff3ac98459a9cb81bc489a1f68b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1080,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u8.png"}},
{
          "id":"18a2ae1632c34d1ca40659744da93487",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":23,
              "y":64},
            "size":{
              "width":340,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba3476ab0f04c4188004f513578d956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":23,
                  "y":64},
                "size":{
                  "width":340,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u22.jpg"}},
{
          "id":"6a9e5249aa0545b0b80f2bcd66d737a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":1080,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd4c4ad66904bd2bdd19cfc03829704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":1080,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u12.png"}},
{
          "id":"25f6030d794140ee9bf7ae2d231d136d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":750,
              "y":170},
            "size":{
              "width":190,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767894b42782483db82805ffff78a3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":750,
                  "y":170},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pinni_b/u8.png"}},
{
          "id":"384d72fa8cb84354bd2fbe1404b54153",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":203,
              "y":230},
            "size":{
              "width":677,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01df7a905f1d46dfb5ded7d50f8b15e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":203,
                  "y":230},
                "size":{
                  "width":677,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pinni_b/u10.png"}},
{
          "id":"9fa83acd1e73402ca9c9b271006188e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":405,
              "y":240},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89c9e579132449bebafb2191b409dd9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":405,
                  "y":240},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pinni_b/u14.png"}},
{
          "id":"771415865ee14e4b8c754f892ecb3f54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":262,
              "y":290},
            "size":{
              "width":560,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92276343939a405dacb2b398c3f72841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":262,
                  "y":290},
                "size":{
                  "width":560,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/p3_s_u2.jpg"}},
{
          "id":"d7a6938c32c5400f87f2a4960cdc4b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":920,
              "y":10},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99486f98690a4259ad71c301d0c038bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":920,
                  "y":10},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pinni_b/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "55cef320cd7c439b9aa2c5aeff7410ac":{
      "scriptId":"u0"},
    "ce592be8a6bf44c2b0b8987d4222f8f3":{
      "scriptId":"u1"},
    "62e4644528f4438da14445d7704b6327":{
      "scriptId":"u2"},
    "07f11ff3ac98459a9cb81bc489a1f68b":{
      "scriptId":"u3"},
    "18a2ae1632c34d1ca40659744da93487":{
      "scriptId":"u4"},
    "8ba3476ab0f04c4188004f513578d956":{
      "scriptId":"u5"},
    "6a9e5249aa0545b0b80f2bcd66d737a0":{
      "scriptId":"u6"},
    "cbd4c4ad66904bd2bdd19cfc03829704":{
      "scriptId":"u7"},
    "25f6030d794140ee9bf7ae2d231d136d":{
      "scriptId":"u8"},
    "767894b42782483db82805ffff78a3d3":{
      "scriptId":"u9"},
    "384d72fa8cb84354bd2fbe1404b54153":{
      "scriptId":"u10"},
    "01df7a905f1d46dfb5ded7d50f8b15e8":{
      "scriptId":"u11"},
    "9fa83acd1e73402ca9c9b271006188e8":{
      "scriptId":"u12"},
    "89c9e579132449bebafb2191b409dd9e":{
      "scriptId":"u13"},
    "771415865ee14e4b8c754f892ecb3f54":{
      "scriptId":"u14"},
    "92276343939a405dacb2b398c3f72841":{
      "scriptId":"u15"},
    "d7a6938c32c5400f87f2a4960cdc4b7f":{
      "scriptId":"u16"},
    "99486f98690a4259ad71c301d0c038bf":{
      "scriptId":"u17"}}});